<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:extns="http://www.tibco.com/namespaces/tnt/plugins/generalactivities/mapper/1763750308440" xmlns:tns="http://www.example.org/schema/1763730461945" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" targetNamespace="http://www.example.org/schema/1763730461945">
    <import namespace="http://www.tibco.com/namespaces/tnt/plugins/generalactivities/mapper/1763750308440"/>
    <element name="UpsertEmpRequest">
    <complexType>
      <sequence>
        <element name="Fname" type="string"/>
                <element minOccurs="0" name="Lname" type="string"/>
                <element name="Salary" type="string"/>
                <element name="EMPID" type="string"/>
                <element name="Status" type="string"/>
            </sequence>
    </complexType>
  </element>
  <element name="UpsertEmpResponse">
    <complexType>
      <sequence>
                <element name="elements" type="extns:Statement">
        </element>
            </sequence>
    </complexType>
  </element>
    <element name="DeleteEmp">
    <complexType>
      <sequence>
        <element name="EmpId" type="integer"/>
      </sequence>
    </complexType>
  </element>
    <element name="operationResponse">
    <complexType>
      <sequence>
        <element name="out" type="string"/>
      </sequence>
    </complexType>
  </element>
    <element name="operation1Request">
    <complexType>
      <sequence>
        <element name="in" type="string"/>
      </sequence>
    </complexType>
  </element>
    <element name="operation1Response">
    <complexType>
      <sequence>
        <element name="out" type="string"/>
      </sequence>
    </complexType>
  </element>
    <element name="DeleteEmpRequest2">
    <complexType>
      <sequence>
        <element name="in" type="string"/>
      </sequence>
    </complexType>
  </element>
    <element name="DeleteEmpResponse1">
    <complexType>
      <sequence>
        <element name="out" type="string"/>
      </sequence>
    </complexType>
  </element>
    <complexType name="DeleteEmpArray">
    <sequence>
      <element maxOccurs="unbounded" minOccurs="0" ref="tns:DeleteEmp"/>
    </sequence>
  </complexType>
    <element name="DeleteEmpArray" type="tns:DeleteEmpArray"/>
</schema>
